public enum BomberSkin
{
    Golden = 0,
    White = 1,
    Gray = 2,
    Black = 3,
    Red = 4,
    Orange = 5,
    Yellow = 6,
    Green = 8,
    Cyan = 9,
    Aqua = 10,
    Blue = 11,
    DarkBlue = 12,
    Purple = 13,
    Magenta = 14,
    Pink = 15,
    Brown = 16,
    DarkGreen = 17,
    Nightmare = 18,
    Gold = 19,
    DarkPurple = 20,
    NeonGreen = 21,
    Alternative1 = 22,
    Alternative2 = 23,
    Alternative3 = 24,
    Alternative4 = 25
}
